name: Build

on:
  push:
    branches:
      - master
      - andrew_gradle_build
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Gradle Build
        run: |
          chmod +x ./2020-code/gradlew
          ./2020-code/gradlew build
          ls
